// Test file to verify course creation functionality
// Run this to test the course creation fix

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'lib/models/course_model.dart';

void main() {
  // Test the CourseModel.toJsonForDatabase method
  print('🧪 Testing CourseModel.toJsonForDatabase method...');
  
  final testCourse = CourseModel(
    id: 'test-id',
    title: 'Test Course',
    description: 'This is a test course',
    instructorId: 'instructor-123',
    instructorName: 'Test Instructor',
    thumbnail: 'https://example.com/thumbnail.jpg',
    category: 'technology',
    createdAt: DateTime.now(),
    isApproved: false,
  );

  print('📝 Course toJson() output:');
  print(testCourse.toJson());
  
  print('\n📝 Course toJsonForDatabase() output:');
  print(testCourse.toJsonForDatabase());
  
  print('\n✅ Test completed. The toJsonForDatabase method should exclude:');
  print('   - id (will be generated by Supabase)');
  print('   - videos array');
  print('   - quizzes array');
  print('   - worksheets array');
  
  print('\n🎯 This should fix the course creation error!');
}
